# Generated by Django 3.2 on 2021-12-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image',
            new_name='photo',
        ),
    ]
