# Generated by Django 3.2 on 2021-12-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_rename_image_menuitem_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(upload_to='Customers/image'),
        ),
    ]
