# Generated by Django 3.2 on 2021-12-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_menuitem_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
