# Generated by Django 3.2 on 2021-12-05 20:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0007_auto_20211204_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='userOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
