# Generated by Django 3.2 on 2021-12-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_auto_20211205_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_time',
            new_name='Date_created',
        ),
    ]
